export const FETCH_DAY = "FETCH_DAY";
export const FETCH_DAY_SCHEDULE = "FETCH_DAY_SCHEDULE";
export const FETCH_WEEK_SCHEDULE = "FETCH_WEEK_SCHEDULE";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const EDIT_SCHEDULE = "EDIT_SCHEDULE";
